### ISSUE TITLE
Initialize GitHub.io

### ISSUE THREAD

**Issue by WenchuanLiliZhao** [WenchuanLiliZhao/WenchuanLiliZhao.GitHub.io#3]
## Install React

Initialize the project with:

```
npm create vite@latest
```

Add this files into the root:

```
.github/workflows/deploy.yaml
```

In `deploy.yaml`, add:

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

In `vite.config.ts`, add a new line:

```typescript
export default defineConfig({
  plugins: [react()],

  base: "/project name"
})
```

## Multiple-page app

```
npm install react-router-dom
```

Make a new navigation for testing the links:

```typescript
import { Link } from "react-router-dom"

export default function Nav() {
  return (
    <ol>
      <li><Link to="/">Overview</Link></li>
      <li><Link to="/about">About</Link></li>
    </ol>
  )
}
```

Make some new pages. For example, create `src/pages/Overview.tsx` and `src/pages/About.tsx`. In `Overview.tsx`:

```typescript
import Nav from "../components/Nav";

export default function About() {
  return (
    <div>
      <Nav></Nav>
      <h1>This is About</h1>
    </div>
  )
}
```

and `About.tsx` is similar.

In `App.tsx`:

```typescript
import './App.css'
import { Routes, Route } from 'react-router-dom' // add this line
import Overview from './pages/Overview' // import Overview
import About from './pages/About' // import About

function App() {

  return (
    <div className="App">
      <Routes>
        <Route index element={<Overview />}/> 
        <Route path='/about' element={<About />}/>
      </Routes>
    </div>
  )
}

export default App
```

In `main.tsx`:

```typescript
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
import { HashRouter } from 'react-router-dom' // Use `HashRouter` instead of `BrowserRouter`. Otherwise, refreshing `https://username.github.io/about` would cause 404.

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  // `basename=?` is essential for GitHub Pages
  <HashRouter basename="/">
    <App />
  </HashRouter>
)
```
